# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26c9e6e9386cbc399435d4ddd91a2c4c98838a3b702581be457f23d8cd20560d85620b8b5fe06265de720ce8b214647ce83083e80373d54e51702581ca28342e

test:
  secret_key_base: fdc169a158fc5877aed75223835ca5331a2b2b56b6e0a3243b9392bd2d1d1876f92646bbcb055dad9f8a6b9693d61edf0aad4767d5cdc5432bf6753a77dc72c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
